select * from v$version where banner like 'Oracle%';


create table producto(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre varchar(50) not null,
    descripcion varchar(50) not null,
    precio_unidad NUMBER(10,3) not null,
    id_categoria integer not null,
    state integer default 1
);

insert into producto(nombre,descripcion,precio_unidad,id_categoria) 
values ('Cuaderno Norma 50 hojas','Cuaderno cuadriculado grande',3500,1);
select producto.nombre from producto,categoria where producto.id_categoria=categoria.id_categoria and producto.id_categoria=1; 
select * from categoria; 
commit;
insert into producto(nombre,descripcion,precio_unidad,id_categoria) 
values ('Lapiz Mirado 2','Lapiz con mina numero 2',700,1);
--//oracle ->insert->tablas externas-> tablas relaes
---
ALTER TABLE producto MODIFY (id_categoria NOT NULL);


------tabla categoría
create table categoria(
    id_categoria integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre varchar(50) not null,
    descripcion varchar(50) not null,
    iva NUMBER(5,2) not null,
    state integer default 1
);

insert into categoria(nombre,descripcion,iva) 
values ('Papelería','Articulosd epapeleria',5);
drop table producto;

ALTER TABLE producto
ADD CONSTRAINT fk_producto_categoria
  FOREIGN KEY (id_categoria)
  REFERENCES categoria(id_categoria);
 -----------------------
 alter table producto
  add codigo varchar(25) default '0' not null;
  select *from producto;
  select categoria.nombre from categoria,producto where producto.id_categoria=categoria.id_categoria and producto.state=1;