SELECT * FROM persona;

-- PROTOTIPOS (INSERT VACIOS)
INSERT INTO persona(NOMBRES, APELLIDOS, NUMERO_IDENTIFICACION, TELEFONO, FECHA_NACIMIENTO, STATE)
	VALUES ();

-- Vendedores
SELECT * FROM OPERADOR o ;
	
INSERT INTO persona(NOMBRES, APELLIDOS, NUMERO_IDENTIFICACION, TELEFONO, FECHA_NACIMIENTO, STATE)
	VALUES ('Luis', 'Sabogal', '3468424', '3229472829', TO_DATE('2020-11-28', 'YYYY-MM-DD'), 1);
INSERT INTO OPERADOR (ROL, ID_PERSONA, STATE, USERNAME, PASSWORD)
	VALUES ('VENDEDOR', 29, 1, 'lsabogal', 'lsabogal');

INSERT INTO persona(NOMBRES, APELLIDOS, NUMERO_IDENTIFICACION, TELEFONO, FECHA_NACIMIENTO, STATE)
	VALUES ('Edison', 'Reyes', '4741480', '313545643', TO_DATE('2020-11-28', 'YYYY-MM-DD'), 1);
INSERT INTO OPERADOR (ROL, ID_PERSONA, STATE, USERNAME, PASSWORD)
	VALUES ('VENDEDOR', 30, 1, 'ereyes', 'ereyes');

-- Clientes
SELECT * FROM CLIENTE c2 ;

INSERT INTO persona(NOMBRES, APELLIDOS, NUMERO_IDENTIFICACION, TELEFONO, FECHA_NACIMIENTO, STATE)
	VALUES ('Mariela', 'Reyes', '1123453', '742345', TO_DATE('2020-11-28', 'YYYY-MM-DD'), 1);
INSERT INTO CLIENTE (FECHA_REGISTRO, ID_PERSONA, STATE)
	VALUES (TO_DATE('1990-11-28', 'YYYY-MM-DD'), 31, 1);

INSERT INTO persona(NOMBRES, APELLIDOS, NUMERO_IDENTIFICACION, TELEFONO, FECHA_NACIMIENTO, STATE)
	VALUES ('Eduardo', 'Galeano', '644657', '742345', TO_DATE('2020-11-28', 'YYYY-MM-DD'), 1);
INSERT INTO CLIENTE (FECHA_REGISTRO, ID_PERSONA, STATE)
	VALUES (TO_DATE('1990-10-28', 'YYYY-MM-DD'), 32, 1);
	
INSERT INTO persona(NOMBRES, APELLIDOS, NUMERO_IDENTIFICACION, TELEFONO, FECHA_NACIMIENTO, STATE)
	VALUES ('Armando', 'Moreno', '6233234', '742345', TO_DATE('2020-11-28', 'YYYY-MM-DD'), 1);
INSERT INTO CLIENTE (FECHA_REGISTRO, ID_PERSONA, STATE)
	VALUES (TO_DATE('1990-01-01', 'YYYY-MM-DD'), 33, 1);
